language: java
install: ./gradlew assemble -x :signArchives
script: ./gradlew clean build jacocoTestReport -x :signArchives
sudo: required
jdk:
  - oraclejdk8
before_install:
  - sudo pip install codecov
after_success:
  - codecov